project:
  type: website
  output-dir: docs

website:
  title: "Melbourne Metrics Lab"
  navbar:
    background: "light"

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
