project:
  type: website
  output-dir: docs

website:
  title: "Melbourne Metrics Lab"
  navbar:
    background: "light"
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Econometrics Workshops"
      - file: index.qmd
        text: "2024"
      - file: workshop2023.qmd
        text: "2023"

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
